package aplicacion.modelo.dominio;
// Generated 07/07/2019 10:04:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {
     private Integer idcategoria;
     private String nombre;
     private String descripcion;
     private Set productoses = new HashSet(0);

    public Categoria() {
    }
    
    public Categoria(int idcategoria) {
        this.idcategoria = idcategoria;
    }

    public Categoria(Integer idcategoria, String nombre, String descripcion) {
        this.idcategoria = idcategoria;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
           
    public Integer getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(Integer idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }
       
    @Override
    public boolean equals(Object other) {
        return (other instanceof Categoria) && (idcategoria != null)? idcategoria.equals(((Categoria)other).idcategoria):(other == this);
    }

    @Override
    public int hashCode() {
        return (idcategoria != null)? (this.getClass().hashCode() + idcategoria.hashCode()):super.hashCode();
    }

    @Override
    public String toString() {
        return String.format("Categoria: [%s,%s]", descripcion, nombre);
    }   
}


